spring:
  application:
    name: api-gateway-linked-config-server
  cloud:
    gateway:
      routes:
        - id: vets-service
          uri: lb://vets-service-linked-config-server
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: lb://visits-service-linked-config-server
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: lb://customers-service-linked-config-server
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
management:
  endpoint:
    gateway:
      enabled: true

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service-linked-config-server: /vet/**
    visits-service-linked-config-server: /visit/**
    customers-service-linked-config-server: /customer/**
    api-gateway-linked-config-server: /gateway/**
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048
# Internationalization
spring.messages.basename: messages/messages
